import {FormEvent,useState} from 'react'; import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {createMappingProfile} from '../../entities/integration/api/integration.api'; import {integrationKeys,integrationQueries} from '../../entities/integration/api/integration.queries'; import {ProblemDetailPanel} from '../../shared/errors/ProblemDetailPanel';
export function MappingProfilesPage(){const qc=useQueryClient(),q=useQuery(integrationQueries.mappingProfiles()); const [code,setCode]=useState(''),[name,setName]=useState(''),[type,setType]=useState('CUSTOMER');
 const m=useMutation({mutationFn:createMappingProfile,onSuccess:async()=>{setCode('');setName('');await qc.invalidateQueries({queryKey:integrationKeys.mappingProfiles()})}});
 const submit=(e:FormEvent)=>{e.preventDefault();if(!m.isPending)m.mutate({code,name,documentType:type})};
 return <div className="integration-page"><header><p className="eyebrow">Integration Setup Center</p><h1>Mapping Studio</h1><p>Профили преобразования канонических CUSTOMER / INVOICE / PAYMENT.</p></header>
 <form className="integration-form" onSubmit={submit}><label>Code<input required value={code} onChange={e=>setCode(e.target.value)}/></label><label>Название<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Document type<select value={type} onChange={e=>setType(e.target.value)}><option>CUSTOMER</option><option>INVOICE</option><option>PAYMENT</option></select></label><button disabled={m.isPending}>Создать mapping</button></form>
 {m.error?<ProblemDetailPanel error={m.error}/>:null}{q.error?<ProblemDetailPanel error={q.error} onRetry={()=>void q.refetch()}/>:null}
 <div className="integration-list">{q.data?.map(x=><div className="integration-list__row" key={x.id}><div><strong>{x.name}</strong><span>{x.code}</span></div><strong>{x.documentType}</strong></div>)}</div></div>}
