import {FormEvent,useState} from 'react';import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';import {useParams} from 'react-router-dom';
import {addSourceField,createSourceSchemaVersion,deleteSourceField,getSourceFields,getSourceSchemaVersions,transitionSourceSchema,validateSourceSchema} from '../../entities/integration/api/integration.api';import {ProblemDetailPanel} from '../../shared/errors/ProblemDetailPanel';
export function SourceSchemaDetailPage(){const id=useParams().schemaId??'',qc=useQueryClient(),versions=useQuery({queryKey:['schema-versions',id],queryFn:()=>getSourceSchemaVersions(id)});const v=versions.data?.[0],fields=useQuery({queryKey:['schema-fields',v?.id],queryFn:()=>getSourceFields(v!.id),enabled:!!v});const [path,setPath]=useState('');
const refresh=async()=>{await qc.invalidateQueries({queryKey:['schema-versions',id]});await qc.invalidateQueries({queryKey:['schema-fields']})};
const newV=useMutation({mutationFn:()=>createSourceSchemaVersion(id,'JSON'),onSuccess:refresh});const add=useMutation({mutationFn:()=>addSourceField(v!.id,{sourcePath:path,detectedType:null,sampleValue:null,required:false,position:null,scope:'DOCUMENT',documentKey:false,valuePolicy:'FIRST_NON_EMPTY'}),onSuccess:async()=>{setPath('');await refresh()}});
const del=useMutation({mutationFn:(fid:string)=>deleteSourceField(v!.id,fid),onSuccess:refresh});const validate=useMutation({mutationFn:()=>validateSourceSchema(v!.id)});const transition=useMutation({mutationFn:(a:'publish'|'reopen'|'archive')=>transitionSourceSchema(v!.id,a),onSuccess:refresh});
const submit=(e:FormEvent)=>{e.preventDefault();if(v&&!add.isPending)add.mutate()};
return <div className="integration-page"><header><p className="eyebrow">Source Schema Studio</p><h1>Schema versions</h1></header><button disabled={newV.isPending} onClick={()=>newV.mutate()}>Новая JSON версия</button>
{v?<section className="integration-panel"><h2>v{v.version} · {v.format} · {v.status}</h2><form className="integration-form" onSubmit={submit}><label>Source path<input required value={path} onChange={e=>setPath(e.target.value)}/></label><button disabled={add.isPending||v.status!=='DRAFT'}>Добавить поле</button></form>
<div className="integration-list">{fields.data?.map(f=><div className="integration-list__row" key={f.id}><div><strong>{f.sourcePath}</strong><span>{f.scope} {f.required?'· required':''}</span></div>{v.status==='DRAFT'?<button onClick={()=>del.mutate(f.id)}>Удалить</button>:null}</div>)}</div>
<div className="integration-actions"><button disabled={v.status!=='DRAFT'||validate.isPending} onClick={()=>validate.mutate()}>Validate</button>{v.status==='DRAFT'?<button disabled={transition.isPending||validate.data?.valid!==true} onClick={()=>transition.mutate('publish')}>Publish</button>:<button disabled={transition.isPending} onClick={()=>transition.mutate('reopen')}>Reopen</button>}</div>
{validate.data?<p><strong>{validate.data.valid?'VALID':'INVALID'}</strong> {validate.data.errors?.length?JSON.stringify(validate.data.errors):''}</p>:null}</section>:null}
{versions.error||fields.error||newV.error||add.error||del.error||validate.error||transition.error?<ProblemDetailPanel error={versions.error||fields.error||newV.error||add.error||del.error||validate.error||transition.error}/>:null}</div>}
