package io.collectra.api.template.preset;

public enum TemplatePresetCode {
    INVOICE_CREATED,
    INVOICE_REMINDER,
    PAYMENT_DUE_SOON,
    PAYMENT_DUE_TODAY,
    PAYMENT_OVERDUE,
    PAYMENT_OVERDUE_ESCALATION,
    PAYMENT_RECEIVED,
    PAYMENT_PARTIALLY_RECEIVED,
    COLLECTION_NOTICE,
    COLLECTION_FINAL_NOTICE,
    CONTRACT_RENEWAL,
    VIP_CUSTOMER_NOTICE
}
