package io.collectra.api.integration.domain;
import jakarta.persistence.*;import java.time.Instant;import java.util.UUID;
@Entity @Table(name="ingestion_batches")
public class IngestionBatch {
 @Id private UUID id; @Column(name="tenant_id",nullable=false) private UUID tenantId; @Column(name="integration_source_id",nullable=false) private UUID integrationSourceId; @Column(name="service_client_id",nullable=false) private UUID serviceClientId;
 @Column(name="idempotency_key",nullable=false,length=200) private String idempotencyKey; @Column(name="request_hash",nullable=false,length=64) private String requestHash; @Column(name="raw_source_file_id",nullable=false) private UUID rawSourceFileId;
 @Column(name="source_schema_version_id") private UUID sourceSchemaVersionId; @Column(name="mapping_profile_version_id") private UUID mappingProfileVersionId; @Column(name="mapping_config_sha256") private String mappingConfigSha256;
 @Enumerated(EnumType.STRING) @Column(nullable=false) private IngestionStatus status; @Column(name="content_type",nullable=false) private String contentType;
 @Column(name="record_count",nullable=false) private int recordCount; @Column(name="accepted_count",nullable=false) private int acceptedCount; @Column(name="reused_count",nullable=false) private int reusedCount; @Column(name="failed_count",nullable=false) private int failedCount;
 @Column(name="received_at",nullable=false) private Instant receivedAt; @Column(name="processing_started_at") private Instant processingStartedAt; @Column(name="completed_at") private Instant completedAt; @Column(name="error_code") private String errorCode; @Column(name="safe_error_message") private String safeErrorMessage;
 @Column(name="context_json",nullable=false,columnDefinition="jsonb") private String contextJson; @Version private long version;
 protected IngestionBatch(){}
 public IngestionBatch(UUID id,UUID tenantId,UUID sourceId,UUID clientId,String key,String hash,UUID fileId,String contentType,Instant receivedAt,String contextJson){this.id=id;this.tenantId=tenantId;this.integrationSourceId=sourceId;this.serviceClientId=clientId;this.idempotencyKey=key;this.requestHash=hash;this.rawSourceFileId=fileId;this.contentType=contentType;this.receivedAt=receivedAt;this.contextJson=contextJson;this.status=IngestionStatus.RECEIVED;}
 public void queue(UUID schemaVersionId,UUID mappingVersionId,String mappingHash){this.sourceSchemaVersionId=schemaVersionId;this.mappingProfileVersionId=mappingVersionId;this.mappingConfigSha256=mappingHash;this.status=IngestionStatus.QUEUED;}
 public void processing(Instant at){if(status!=IngestionStatus.QUEUED)throw new IllegalStateException("Ingestion is not queued");status=IngestionStatus.PROCESSING;processingStartedAt=at;}
 public void complete(int total,int accepted,int reused,int failed,Instant at){recordCount=total;acceptedCount=accepted;reusedCount=reused;failedCount=failed;status=failed==0?IngestionStatus.COMPLETED:accepted+reused>0?IngestionStatus.PARTIALLY_COMPLETED:IngestionStatus.FAILED;completedAt=at;}
 public void fail(String code,String message,Instant at){status=IngestionStatus.FAILED;errorCode=code;safeErrorMessage=message;completedAt=at;}
 public UUID getId(){return id;} public UUID getTenantId(){return tenantId;} public UUID getIntegrationSourceId(){return integrationSourceId;} public UUID getServiceClientId(){return serviceClientId;} public String getIdempotencyKey(){return idempotencyKey;} public String getRequestHash(){return requestHash;} public UUID getRawSourceFileId(){return rawSourceFileId;} public UUID getMappingProfileVersionId(){return mappingProfileVersionId;} public IngestionStatus getStatus(){return status;} public String getContentType(){return contentType;} public int getRecordCount(){return recordCount;} public int getAcceptedCount(){return acceptedCount;} public int getReusedCount(){return reusedCount;} public int getFailedCount(){return failedCount;} public Instant getReceivedAt(){return receivedAt;} public String getErrorCode(){return errorCode;} public String getSafeErrorMessage(){return safeErrorMessage;}
}
