package io.collectra.api.integration.application;
import io.collectra.api.file.application.FileService;import io.collectra.api.importing.application.*;import io.collectra.api.integration.infrastructure.*;import java.time.Clock;import java.util.UUID;import org.springframework.stereotype.Service;import org.springframework.transaction.support.TransactionTemplate;import org.springframework.transaction.PlatformTransactionManager;
@Service public class IngestionWorker{
 private final IngestionBatchRepository batches;private final IngestionRecordDiagnosticRepository diagnostics;private final FileService files;private final MappingExecutionService mappings;private final BusinessRecordPersistenceService persistence;private final Clock clock;private final TransactionTemplate tx;
 public IngestionWorker(IngestionBatchRepository batches,IngestionRecordDiagnosticRepository diagnostics,FileService files,MappingExecutionService mappings,BusinessRecordPersistenceService persistence,Clock clock,PlatformTransactionManager tm){this.batches=batches;this.diagnostics=diagnostics;this.files=files;this.mappings=mappings;this.persistence=persistence;this.clock=clock;this.tx=new TransactionTemplate(tm);}
 public void process(UUID tenantId,UUID id){var b=tx.execute(s->{var x=batches.findByIdAndTenantId(id,tenantId).orElseThrow();if(x.getStatus()!=io.collectra.api.integration.domain.IngestionStatus.QUEUED)return null;x.processing(clock.instant());return batches.saveAndFlush(x);});if(b==null)return;
  try(var input=files.openContent(tenantId,b.getRawSourceFileId()).content()){byte[] content=input.readAllBytes();var mapped=mappings.executeBatch(tenantId,b.getMappingProfileVersionId(),content);int accepted=0,reused=0,failed=0;
   for(var d:mapped.documents()){try{var result=persistence.persist(tenantId,mapped.documentType(),d.normalizedPayload());if(result.created())accepted++;else reused++;diagnostics.save(new io.collectra.api.integration.domain.IngestionRecordDiagnostic(tenantId,id,d.order(),d.documentKey(),result.created()?"ACCEPTED":"REUSED","PERSISTENCE",result.type(),result.id(),result.externalId(),null,null,clock.instant()));}catch(BusinessRecordConflictException ex){failed++;diagnostics.save(new io.collectra.api.integration.domain.IngestionRecordDiagnostic(tenantId,id,d.order(),d.documentKey(),"FAILED","PERSISTENCE",ex.type(),null,ex.externalId(),"BUSINESS_IDENTITY_CONFLICT","External identity conflicts with existing canonical state",clock.instant()));}catch(RuntimeException ex){failed++;diagnostics.save(new io.collectra.api.integration.domain.IngestionRecordDiagnostic(tenantId,id,d.order(),d.documentKey(),"FAILED","PERSISTENCE",mapped.documentType(),null,null,"BUSINESS_VALIDATION_FAILED","Business record validation failed",clock.instant()));}}
   int a=accepted,r=reused,f=failed,total=mapped.documents().size();tx.executeWithoutResult(s->{var x=batches.findByIdAndTenantId(id,tenantId).orElseThrow();x.complete(total,a,r,f,clock.instant());batches.save(x);});
  }catch(Exception ex){tx.executeWithoutResult(s->{var x=batches.findByIdAndTenantId(id,tenantId).orElseThrow();x.fail("INGESTION_PROCESSING_FAILED","Ingestion processing failed",clock.instant());batches.save(x);});}
 }
}
